# Site settings
title: Abhinav Kaushik
description: Abhinav Kaushik
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Abhinav Kaushik
user_description: >
                    I'm an independent consultant with more than 10 years of experience in software development
                    in fields ranging from supply chain to legal discovery. I am a full stack developer and I code primarily in Python, Django and Javascript.
                    Over the years, I have helped startups launch MVPs,
                    revamp their existing products and overhaul their architecture. I get involved in the whole process right from ironing out the requirements to
                    deployment automation of the product. I'm experienced in setting up high availability webapps on AWS. Information security is an
                    area of interest for me and it's an integral part of all my work (not just an afterthought!)
user_description2: >
                    I'm available for freelance work. If you are looking to hire me, send me an email on abhinav.kaushik@gmail.com
user_title: Web Developement Consultant
email: abhinav.kaushik@gmail.com
twitter_username: lorem_ipsum
github_username:  lazyfunctor
gplus_username:  lorem_ipsum
linkedin_profile: https://www.linkedin.com/in/abhinav-kaushik-8a6a268/

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
